### ISSUE TITLE
[Bug]: cant change names

### ISSUE THREAD

**Issue by mpl1337** [Jey-Cee/ioBroker.net-tools#12]
### What happened?

hello, iv try to change the name from the devices, i change it from "192.168.178.1" to "Fritzbox", after few minutes the adapter change the name back to "192.168.178.1" with every device the same problem

### Adapter Version

0.1.7

### JS-Controller Version

5.2.16

### Node JS Version

12.22.7

### NPM Version

6.14.15

### Operating System

Debian

**Comment by Jey-Cee** [comment]
You have to change the name on the objects for the device. 
I wont fix this issue, as the whole configuration will be rewritten in near future.

**Comment by Jey-Cee** [comment]
Done with v1.x.x
