### ISSUE TITLE
Google 8.8.8.8 kann nicht hinzugefügt werden

### ISSUE THREAD

**Issue by capitaenz** [Jey-Cee/ioBroker.net-tools#13]
### Contact Details

capitaenz@gmx.net

### What happened?

Google 8.8.8.8 kann nicht hinzugefügt werden.
Der Eintrag wird ignoriert...

### Adapter Version

0.1.7

### JS-Controller Version

3.3.22

### Node JS Version

14.18.2

### NPM Version

6.14.15

### Operating System

Debian

**Comment by Jey-Cee** [comment]
Was heist kann nicht hinzugefügt werden? Bitte eine bessere Beschreibung des Problems.

**Comment by capitaenz** [comment]
Sorry, hier eine genauere Beschreibung:
- ich gehe auf "Instanzeinstellungen: net-tools.0"
- klicke "Geräte"
- trage ala Namen "google" ein und als IP "8.8.8.8"
- Der Eintrag wird nicht gespeichert

**Comment by Jey-Cee** [comment]
Das kann nicht funktionieren, es muss eine MAC Adresse angegeben werden. Die kann der Adapter nicht Automatisch ermitteln.

Man sollte es Unterlassen öffentliche Server zu Pingen, außer man hat die Einverständnis des Betreibers. Sowas kann auch mal als Angriff gewertet werden oder es Überlastet den Server des Dienstes einfach nur.
