### ISSUE TITLE
[Feature] Optionally use devicenames or IP Address for states

### ISSUE THREAD

**Issue by mcm1957** [Jey-Cee/ioBroker.net-tools#19]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
States are currently created based on the max address. It would be much more comfortable to base the states on the devicename or the ip-address. Both are normally known by ser while mac addresses rearely are wellknown. The keep compatibility the format could / should be settable by an (glocbel) parameter.

**Describe alternatives you've considered**
Using Alias would be possible but adds additional overhead

**Additional context**
![image](https://user-images.githubusercontent.com/28575778/206779213-bab674a4-37f7-414e-a5dc-8e552f7866c2.png)

**Comment by Jey-Cee** [comment]
You as developer must know the law that adapter has to use a unique id, that will not change. Ip and name are not unique and can change. 
There are old adapter they do not respect this, but they are the reason for this law.

**Comment by mcm1957** [comment]
Well, I did / do NOT know that state keys must be unique in the sense that they may not be defined by the user during configuration of the adapter. If this is specified in some documention, please let me know where - maybe there are other rules I do not know yet.

Anyway, I accept that you do not plan to modify this adapter.
