### ISSUE TITLE
within a buanet docker setup only macvlan range ist searched

### ISSUE THREAD

**Issue by EdgarM73** [Jey-Cee/ioBroker.net-tools#23]
when iobroker is setup with buanet docker container with macvlan, than only the subnet is seahed for new devices, not the complete network which should be still known.

One solution would be, to use the ip range mask  for searching devices

other solution would be to add fields to the admin page which range should be disovered.

regards
E

**Comment by Jey-Cee** [comment]
The search is done by discovery adapter, there is already a issue for adding expert settings. 
https://github.com/ioBroker/ioBroker.discovery/issues/224
