### ISSUE TITLE
Option for number of failed/successful pings before 'alive' state is updated

### ISSUE THREAD

**Issue by raintonr** [Jey-Cee/ioBroker.net-tools#25]
I use net-tools to monitor our internet connection by pinging several reliable hosts.

This has been working well but packet loss is a thing and sometimes a single missed ping doesn't indicate the 'host' is actually unavailable - rather there may be a slight glitch in the network.

It would be useful to have a setting that allows for a number of missed pings before setting alive to false. On the flip side, maybe also require some number (> 1) of successful pings before marking alive as true.

This is very similar to how the [OpenWrt mwan3 package](https://openwrt.org/docs/guide-user/network/wan/multiwan/mwan3#interface_configuration) or [Loxone's Ping Block](https://www.loxone.com/enen/kb/ping-function-block/) work.

**Comment by Jey-Cee** [comment]
Added in v1.x.x
