### ISSUE TITLE
Different IP ranges to select

### ISSUE THREAD

**Issue by Guenter-1953** [Jey-Cee/ioBroker.net-tools#26]
I use a Unifi Network with some Vlan´s with different IP ranges. 
It would be nice to select different IP ranges, such as 192.168.1.1-192.168.1.254 , 192.168.100.1-192.168.100.254 etc. Cause I have a main-network, a CAM-network and a IoT-network.

**Comment by Jey-Cee** [comment]
Looks like the same as #23

**Comment by Guenter-1953** [comment]
These are two different things. In #23 EdgarM73 spoke about a MACVLAN. How to create and to understand what it means look here:; https://docs.docker.com/network/macvlan/

It´s a part of IP´s in a 192.168.x.x/24 network.

I mean normal IP ranges which know each other in a normal VLAN virtual network), such you can create in a Unifi network. see here: https://help.ui.com/hc/en-us/articles/9761080275607-UniFi-Network-Creating-Virtual-Networks-VLANs-

**Comment by Jey-Cee** [comment]
Hm you didn't read my comment /the linked issue or understand it.
You will use the discovery function which is limited to the subnetwork of the host, this function is not part of net-tools, it is part of the discovery adapter.
If you add your device manual in net-tools, the ping function is working as it should.

**Comment by Guenter-1953** [comment]
I added by hand  my other devices in the other subnet and it works. Nice would be when this works automaticly after I declared the range of the other subnet (better other IP range). But may be my wishes are to complicated to find a solution.

**Comment by Ilovegym66** [comment]
Hi, some hints:
 the scan depends on the subnetmask, if you have only /24 (255.255.255.0) , the range is from 0-254 in the current subnet.  (like 192.168.1.0 - 192.168.1.254).
If you need to scan another subnet, you have to change your subnetmask to the range..  a /23 have 2 subnets, like 192.168.1.x and 192.168.2.x 
for more details google for subnetting  :) 
In summary this issue depends not on the adapter, it's a physical network infrastructure design problem.. :)

**Comment by Jey-Cee** [comment]
Done with 1.0.6
