### ISSUE TITLE
Update auf 1.0.1 = File not found

### ISSUE THREAD

**Issue by Brainbug01** [Jey-Cee/ioBroker.net-tools#28]
### What happened?

Bekomme ein Update auf 1.0.1 angeboten:

![Screenshot_2024-01-20-10-34-01-886_com android chrome-edit](https://github.com/Jey-Cee/ioBroker.net-tools/assets/35106961/0f01f1d1-f1e2-45b3-b105-fb33ef377d9a)

Wenn ich rechts auf das ? klicke kommt eine leere Seite:
https://github.com/jey-cee/ioBroker.net-tools/blob/main/README.md

![Screenshot_2024-01-20-10-39-06-733_com android chrome-edit](https://github.com/Jey-Cee/ioBroker.net-tools/assets/35106961/0045d806-1ec6-4e03-bb5a-8e79c09ffd6a)

### Adapter Version

0.2.0

### JS-Controller Version

5.0.17

### Node JS Version

18.19.0

### NPM Version

10.2.3

### Operating System

Debian

**Comment by Jey-Cee** [comment]
Thank you for this report. For now you can read here: https://github.com/Jey-Cee/ioBroker.net-tools/blob/master/README.md
