### ISSUE TITLE
[Bug]: Invalid property licenseInformation

### ISSUE THREAD

**Issue by foxriver76** [Jey-Cee/ioBroker.net-tools#32]
### What happened?

Please stick to the schema for `licenseInformation` 

https://github.com/Jey-Cee/ioBroker.net-tools/blob/eb55fb7796c817227b06159a97fd6c0ca7be3adb/io-package.json#L99

### Adapter Version

GitHub

### JS-Controller Version

1

### Node JS Version

1

### NPM Version

1

### Operating System

Ubuntu

**Comment by mcm1957** [comment]
@Jey-Cee 
looks like solved in the meantime
