### ISSUE TITLE
[cosmetic] German Adapter Title NETZWERK ZEUGE / NETZ WERKZEUGE

### ISSUE THREAD

**Issue by mcm1957** [Jey-Cee/ioBroker.net-tools#34]
The german description NETZWERKZEUGE looks like  NETZWERK-ZEUGE - not really a useable phrase:

![image](https://github.com/Jey-Cee/ioBroker.net-tools/assets/28575778/f36b7887-4c91-4209-8a4d-39c2f0570903)

Eventually consider using NETZWERKWERKZEUGE (or NETZWERK WERKZEUGE) as german text.

Consider this only as a hit and feel free to close without further comment if you fell everything is OK anyway.

**Comment by Jey-Cee** [comment]
Thanks. Changed with 1.0.6
