### ISSUE TITLE
[Bug]: Please fix io-package.json

### ISSUE THREAD

**Issue by mcm1957** [Jey-Cee/ioBroker.net-tools#35]
### Contact Details

use telegram channel

### What happened?

io-package.json contains invalid entry licenseInformation.
Please fix.

```
    "licenseInformation": {
      "type": "paid",
      "license": "....",
      "url": :... link to license datails, shop etc ..."
    },
```

For details see schema.

Please update testing to 4.1.1 otherwise tests will fail.

### Adapter Version

github

### JS-Controller Version

n/a

### Node JS Version

n/a

### NPM Version

n/a

### Operating System

Ubuntu

**Comment by Jey-Cee** [comment]
Can you explain what is wrong with licenseInformation entry? I do not see a problem.
Thanks for the hint with testing.

**Comment by mcm1957** [comment]
Sorry, I must have looked at the old version. You fixed it 2 days ago already.

BUT 
The link should NOT point to the description of the license but to an information page specifix for tha adapter describing
-) restrictions for free version (not applicable here)
-) prices including duration of license (lidetime, yearly fee, version spcific, ...)
-) link to shop
-) information about seller including contact address to clearify that the adapter is not sold by ioBroker gmbh.


Additional Question:
Did you negotiate with bluefox this paid adapter already?
If not please contact bluefox immidiatly. No paid adapter is allowed at any repository without confirmation by bluefox as ioBroker Gmbh will request license fees.
