### ISSUE TITLE
Adapter net-tools causing high load[Bug]: 

### ISSUE THREAD

**Issue by Visioneer3** [Jey-Cee/ioBroker.net-tools#37]
### Contact Details

michael.frey@outlook.com

### What happened?

Nach Update auf die Verision 1.06 steigt die Last des Systems signifikant um ca. 20%. HTOP zeigt net-tools als Auslöser. Nach stoppen sinkt die Systemlast wirde auf Normalwert. 

### Adapter Version

1.06

### JS-Controller Version

5.0.19

### Node JS Version

18.17.1

### NPM Version

9.6.7

### Operating System

Debian

**Comment by Jey-Cee** [comment]
Wie sieht die Konfiguration des Adapters aus?

**Comment by Visioneer3** [comment]
Standard, Scan-Intervall 60 Sekunden, Suche über den Ethernet Adapter enp1s0
Class-C Netz, keine Einschränkung der Adressen

Ports sind in Voreinstellung

***@***.***

Von: Christoph Gerle ***@***.***>
Gesendet: Mittwoch, 20. März 2024 20:34
An: Jey-Cee/ioBroker.net-tools ***@***.***>
Cc: Visioneer3 ***@***.***>; Author ***@***.***>
Betreff: Re: [Jey-Cee/ioBroker.net-tools] Adapter net-tools causing high load[Bug]: (Issue #37)


Wie sieht die Konfiguration des Adapters aus?

-

**Comment by Jey-Cee** [comment]
Heist du hast die Automatische Suche nicht eingeschalten?
Wieviele Geräte hast du in deinem Netz?

**Comment by Visioneer3** [comment]
Doch, die ist eingeschaltet. Habe jetzt die Werte mal hochgesetzt. Die Last ist dann niedriger.

***@***.***

Von: Christoph Gerle ***@***.***>
Gesendet: Mittwoch, 20. März 2024 22:36
An: Jey-Cee/ioBroker.net-tools ***@***.***>
Cc: Visioneer3 ***@***.***>; Author ***@***.***>
Betreff: Re: [Jey-Cee/ioBroker.net-tools] Adapter net-tools causing high load[Bug]: (Issue #37)


Heist du hast die Automatische Suche nicht eingeschalten?
Wieviele Geräte hast du in deinem Netz?

-

**Comment by Jey-Cee** [comment]
Ich hab das Problem gefunden und behoben. Bitte die 1.0.11 Testen.
