### ISSUE TITLE
[Bug]: Net-Tools fails to resolve Mac-Address of localhost

### ISSUE THREAD

**Issue by TKS74** [Jey-Cee/ioBroker.net-tools#40]
### Contact Details

tks@sadi.ws

### What happened?

The ioBroker Log shows up an error periodically (almost) every minute:
Discovery and Ping Instances are installed and running.

The IP Address in the log is the Address of the physical ioBroker Localhost (RaspberryPi4).
How can i get rid of this logging?

### Adapter Version

1.0.11

### JS-Controller Version

5.0.19

### Node JS Version

18.20.0

### NPM Version

10.5.0

### Operating System

Debian

### Relevant log output

```shell
net-tools.0
	2024-04-21 00:57:49.625	info	Discovery finished
net-tools.0
	2024-04-21 00:57:45.101	info	MAC address for 192.168.2.120: null
net-tools.0
	2024-04-21 00:57:45.061	info	Can not get mac for 192.168.2.120. Going to next IP.
```

### Anything else?

![grafik](https://github.com/Jey-Cee/ioBroker.net-tools/assets/167654707/230bf234-4e14-4fdc-82ba-1f95b70a311e)

**Comment by Jey-Cee** [comment]
It is not possible to prevent this message. You can change the log level for the instance from info to warn.
That it it appears every minute is a result of your cron:
At every minute past every 24th hour.
It is a bad idea to start the auto discovery every minute and can result in a high system load.

I also think that your default ping interval is not what you want. 30000 s = 8.33 h

The discovery adapter was removed as dependency and is no longer needed. Ping was never a dependency.

**Comment by TKS74** [comment]
It wasn't my intention to run auto discovery every minute.
I wanted to start it once a day, but it looks like i had problems to configure it.
Now it looks like it is working correctly with * */24 * * *

The ping setting of 30000 s ist not what the instance is doing.
My Alive DPs are refreshed every 30 s, so no need to reconfigure something here.

As the error messages in the log appear one time a day from now on, i don't wan't to go into further configuration steps.
(I don't know how to change a log level anyway)
I'm glad that it's working in a good way now, thank you!
