### ISSUE TITLE
Instanz startet sich neu

### ISSUE THREAD

**Issue by Curtis777** [Jey-Cee/ioBroker.net-tools#5]
**Describe the bug**  
frisch installierter adapter.
sobald ich ihn starte und in den settings auf geräte suchen klicke startet die instanz neu

**To Reproduce**  
Instanz gestartet 
klicke auf settings
Tab Geräte
Geräte suchen
Log Eintrag erscheint

**Expected behavior**  
einen Start der Gerätesuche

**Screenshots & Logfiles**  
<html>
<body>

net-tools.0 | 2021-06-24 20:57:16.239 | info | (1348) starting. Version 0.1.5 in /opt/iobroker/node_modules/iobroker.net-tools, node: v12.22.1, js-controller: 3.2.16
-- | -- | -- | --
net-tools.0 | 2021-06-24 20:56:44.738 | warn | (1292) Terminated (UNCAUGHT_EXCEPTION): Without reason
net-tools.0 | 2021-06-24 20:56:44.738 | info | (1292) terminating
net-tools.0 | 2021-06-24 20:56:44.230 | error | (1292) Cannot read property 'val' of null
net-tools.0 | 2021-06-24 20:56:44.230 | error | at discover (/opt/iobroker/node_modules/iobroker.net-tools/main.js:205:19)
net-tools.0 | 2021-06-24 20:56:44.230 | error | (1292) TypeError: Cannot read property 'val' of null
net-tools.0 | 2021-06-24 20:56:44.229 | error | (1292) unhandled promise rejection: Cannot read property 'val' of null
net-tools.0 | 2021-06-24 20:56:44.229 | error | (1292) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
net-tools.0 | 2021-06-24 20:54:39.919 | info | (1292) starting. Version 0.1.5 in /opt/iobroker/node_modules/iobroker.net-tools, node: v12.22.1, js-controller: 3.2.16

</body>
</html>

**Versions:**  
 - Adapter version: 0.1.5
 - JS-Controller version: NPM 6.14.12
 - Node version: v12.22.1
 - Operating system: Docker container

**Additional context**

**Comment by Jey-Cee** [comment]
discovery Adapter nicht installiert?
