### ISSUE TITLE
Devices cant be deleted or modified 

### ISSUE THREAD

**Issue by tehmilcho** [Jey-Cee/ioBroker.net-tools#7]
**Describe the bug**  
It is not possible to create, delete or modify devices.

For example:
I had created my computer manually, after multiple attempts it was eventually saved. However, I had saved it without "pinging" it. Now I wanted to change this and have set the hook at Ping. After saving the settings, the Apdater restarts and the hook is removed again.

I have then completely reinstalled the adapter and let the devices automatically detected now I just wanted to delete, after deleting and saving the adapter restarts and all devices are there again. 

Also is now not possible to disable the ping for the devices.  Changing Settings on "Main Settings" works fine.

**Screenshots & Logfiles**  
Log after changing the Settings:
```
net-tools.0 | 2021-07-01 21:02:51.754 | info | (30921) Scanning for open ports at localhost, please wait
net-tools.0 | 2021-07-01 21:02:51.723 | info | (30921) starting. Version 0.1.5 in /opt/iobroker/node_modules/iobroker.net-tools, node: v12.22.1, js-controller: 3.3.10
net-tools.0 | 2021-07-01 21:02:48.470 | info | (26157) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
net-tools.0 | 2021-07-01 21:02:48.469 | info | (26157) terminating
net-tools.0 | 2021-07-01 21:02:47.963 | info | (26157) Got terminate signal TERMINATE_YOURSELF
```

**Versions:**  
 - Adapter version: 0.1.5
 - JS-Controller version: 3.3.10 
 - Node version: 12+ 
 - Operating system: Ubuntu Server

**Comment by ddsak** [comment]
Same here on Raspberry with adapter 0.1.5, Note 12.22.2 and JS-Controller 3.3.14

**Comment by Jey-Cee** [comment]
I can confirm:
- it is not possible to change the settings for a device
- it is not possible to delete the device within the config

**Comment by Jey-Cee** [comment]
Fixed with versio. 0.1.7
